-- Campus Lost & Found - initial schema.
-- Written to run identically on PostgreSQL (production) and H2 in PostgreSQL mode (tests).
-- Rules kept portable: IDENTITY columns, CHECK IN (...) lists (immutable), explicit
-- ON DELETE behaviour, no partial indexes, no function indexes, no now() in CHECK.
-- "Not in the future", "one open flag per user", and status transitions are enforced in
-- the service layer (see docs/design-decisions.md DD-2).

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(254) NOT NULL,
    display_name        VARCHAR(60)  NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    role                VARCHAR(20)  NOT NULL DEFAULT 'USER',
    email_verified      BOOLEAN      NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_users_email        UNIQUE (email),
    CONSTRAINT ck_users_email_lower  CHECK (email = LOWER(email)),
    CONSTRAINT ck_users_role         CHECK (role IN ('USER', 'MODERATOR', 'ADMIN')),
    CONSTRAINT ck_users_display_name CHECK (LENGTH(TRIM(display_name)) >= 2)
);

-- ---------------------------------------------------------------------------
-- email_verification_tokens  (opaque token; only its hash is stored)
-- ---------------------------------------------------------------------------
CREATE TABLE email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMP    NOT NULL,
    consumed_at TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_evt_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_evt_user ON email_verification_tokens (user_id);

-- ---------------------------------------------------------------------------
-- listings
--   kind          LOST | FOUND
--   private_details  identifying details deliberately withheld from public view;
--                    visible only to the reporter + moderators, used by the matching
--                    engine and the claim-verification step (see DD-4).
-- ---------------------------------------------------------------------------
CREATE TABLE listings (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id                 BIGINT        NOT NULL REFERENCES users (id),
    kind                        VARCHAR(10)   NOT NULL,
    title                       VARCHAR(120)  NOT NULL,
    description                 VARCHAR(2000) NOT NULL,
    category                    VARCHAR(40)   NOT NULL,
    location_text               VARCHAR(200),
    building                    VARCHAR(80),
    area                        VARCHAR(80),
    event_date                  DATE          NOT NULL,
    private_details             VARCHAR(1000),
    status                      VARCHAR(15)   NOT NULL DEFAULT 'OPEN',
    created_at                  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                     BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_listings_kind   CHECK (kind IN ('LOST', 'FOUND')),
    CONSTRAINT ck_listings_status CHECK (status IN ('OPEN', 'MATCHED', 'RECOVERED', 'CLOSED', 'REMOVED')),
    CONSTRAINT ck_listings_category CHECK (category IN (
        'ELECTRONICS','PHONE','LAPTOP','TABLET','HEADPHONES','CHARGER_CABLE','CAMERA',
        'BAGS','WALLET_PURSE','KEYS','ID_CARD','CLOTHING','JEWELRY','EYEWEAR',
        'WATER_BOTTLE','BOOKS_NOTES','STATIONERY','SPORTS_EQUIPMENT','UMBRELLA',
        'MUSICAL_INSTRUMENT','MEDICAL','PET','OTHER'))
);
CREATE INDEX ix_listings_kind_status ON listings (kind, status);
CREATE INDEX ix_listings_category    ON listings (category);
CREATE INDEX ix_listings_building    ON listings (building);
CREATE INDEX ix_listings_event_date  ON listings (event_date);
CREATE INDEX ix_listings_reporter    ON listings (reporter_id);

-- ---------------------------------------------------------------------------
-- listing_attributes  (controlled key/value; the public structured match surface)
-- ---------------------------------------------------------------------------
CREATE TABLE listing_attributes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT      NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    attr_key   VARCHAR(20) NOT NULL,
    attr_value VARCHAR(60) NOT NULL,
    CONSTRAINT ck_attr_key CHECK (attr_key IN
        ('COLOR','BRAND','MATERIAL','SIZE','MODEL','PATTERN','OTHER')),
    CONSTRAINT uq_attr_triple UNIQUE (listing_id, attr_key, attr_value)
);
CREATE INDEX ix_attr_listing ON listing_attributes (listing_id);

-- ---------------------------------------------------------------------------
-- match_candidates  (one row per (lost, found) pair scored at/above threshold)
--   score          0..100, equal to the sum of its match_reasons.contribution
--   scorer_version stamp so a later weight change is detectable / re-scoreable
-- ---------------------------------------------------------------------------
CREATE TABLE match_candidates (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lost_listing_id  BIGINT      NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    found_listing_id BIGINT      NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    score            INTEGER     NOT NULL,
    status           VARCHAR(12) NOT NULL DEFAULT 'SUGGESTED',
    scorer_version   VARCHAR(16) NOT NULL,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version          BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT ck_mc_score  CHECK (score >= 0 AND score <= 100),
    CONSTRAINT ck_mc_status CHECK (status IN ('SUGGESTED', 'CONFIRMED', 'REJECTED')),
    CONSTRAINT ck_mc_distinct CHECK (lost_listing_id <> found_listing_id),
    CONSTRAINT uq_mc_pair UNIQUE (lost_listing_id, found_listing_id)
);
CREATE INDEX ix_mc_lost   ON match_candidates (lost_listing_id);
CREATE INDEX ix_mc_found  ON match_candidates (found_listing_id);

-- ---------------------------------------------------------------------------
-- match_reasons  (human-readable "why", additive: SUM(contribution) = score)
-- ---------------------------------------------------------------------------
CREATE TABLE match_reasons (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT       NOT NULL REFERENCES match_candidates (id) ON DELETE CASCADE,
    signal       VARCHAR(20)  NOT NULL,
    detail       VARCHAR(300) NOT NULL,
    contribution INTEGER      NOT NULL,
    CONSTRAINT ck_mr_signal CHECK (signal IN
        ('CATEGORY','KEYWORDS','LOCATION','DATE','ATTRIBUTES')),
    CONSTRAINT ck_mr_contribution CHECK (contribution >= 0 AND contribution <= 100)
);
CREATE INDEX ix_mr_candidate ON match_reasons (candidate_id);

-- ---------------------------------------------------------------------------
-- claims  (ownership-verification workflow for a FOUND listing; see DD-5)
-- ---------------------------------------------------------------------------
CREATE TABLE claims (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id         BIGINT        NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    claimant_id        BIGINT        NOT NULL REFERENCES users (id),
    match_candidate_id BIGINT        REFERENCES match_candidates (id) ON DELETE SET NULL,
    answer_text        VARCHAR(1000) NOT NULL,
    status             VARCHAR(12)   NOT NULL DEFAULT 'PENDING',
    decided_by         BIGINT        REFERENCES users (id),
    decision_note      VARCHAR(1000),
    decided_at         TIMESTAMP,
    created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version            BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_claims_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN'))
);
CREATE INDEX ix_claims_listing  ON claims (listing_id);
CREATE INDEX ix_claims_claimant ON claims (claimant_id);

-- ---------------------------------------------------------------------------
-- contact_messages  (in-app; parties never exchange email/phone)
-- ---------------------------------------------------------------------------
CREATE TABLE contact_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id   BIGINT        NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    sender_id    BIGINT        NOT NULL REFERENCES users (id),
    recipient_id BIGINT        NOT NULL REFERENCES users (id),
    body         VARCHAR(2000) NOT NULL,
    read_at      TIMESTAMP,
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cm_distinct CHECK (sender_id <> recipient_id)
);
CREATE INDEX ix_cm_recipient ON contact_messages (recipient_id);
CREATE INDEX ix_cm_sender    ON contact_messages (sender_id);
CREATE INDEX ix_cm_listing   ON contact_messages (listing_id);

-- ---------------------------------------------------------------------------
-- flags  (report a suspicious / incorrect listing; moderation queue)
-- ---------------------------------------------------------------------------
CREATE TABLE flags (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id      BIGINT        NOT NULL REFERENCES listings (id) ON DELETE CASCADE,
    reporter_id     BIGINT        NOT NULL REFERENCES users (id),
    reason          VARCHAR(20)   NOT NULL,
    details         VARCHAR(1000),
    status          VARCHAR(12)   NOT NULL DEFAULT 'OPEN',
    resolved_by     BIGINT        REFERENCES users (id),
    resolution_note VARCHAR(1000),
    resolved_at     TIMESTAMP,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version         BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_flags_reason CHECK (reason IN
        ('SPAM','SCAM','OFFENSIVE','WRONG_INFO','PROHIBITED_ITEM','OTHER')),
    CONSTRAINT ck_flags_status CHECK (status IN ('OPEN','REVIEWED','ACTIONED','DISMISSED'))
);
CREATE INDEX ix_flags_status  ON flags (status);
CREATE INDEX ix_flags_listing ON flags (listing_id);
